#pragma once


namespace zcockpit::cockpit::hardware
{
	enum class FwdSwitchPosition : unsigned {
		starter1_pos_gnd,
		starter1_pos_off,
		starter1_pos_cont,
		starter1_pos_flt,
		starter2_pos_gnd,
		starter2_pos_off,
		starter2_pos_cont,
		starter2_pos_flt,
		drive_disconnect1_pos_generator_disconnect_up,
		drive_disconnect1_pos_generator_disconnect_down,
		air_valve_manual_outflow_valve_open,
		air_valve_manual_outflow_valve_middle,
		air_valve_manual_outflow_valve_close,
		alt_flaps_pos_alternate_flaps_arm,
		alt_flaps_pos_alternate_flaps_off,
		flt_ctr_b_pos_flight_control_b_on,
		flt_ctr_b_pos_flight_control_b_off,
		flt_ctr_b_pos_flight_control_b_stbyrud,
		flt_ctr_a_pos_flight_control_a_on,
		flt_ctr_a_pos_flight_control_a_off,
		flt_ctr_a_pos_flight_control_a_stbyrud,
		alt_flaps_ctrl_alternate_flaps_ctrl_dn,
		alt_flaps_ctrl_alternate_flaps_ctrl_off,
		alt_flaps_ctrl_alternate_flaps_ctrl_up,
		dspl_source_instrument_displays_source_1,
		dspl_source_instrument_displays_source_2,
		dspl_source_instrument_displays_source_auto,
		irs_source_fms_irs_tfr_r,
		irs_source_fms_irs_tfr_normal,
		irs_source_fms_irs_tfr_l,
		vhf_nav_source_fms_vhf_nav_l,
		vhf_nav_source_fms_vhf_nav_normal,
		vhf_nav_source_fms_vhf_nav_r,
		max_allowable_altitude,landing_alt,
		spoiler_b_pos_off,
		spoiler_b_pos_on,
		spoiler_a_pos_off,
		spoiler_a_pos_on,
		wing_heat_pos_on,
		wing_heat_pos_off,
		eng1_heat_pos_off,
		eng1_heat_pos_on,
		duct_ovht_test_pos_on,
		duct_ovht_test_pos_off,
		r_recirc_fan_pos_auto,
		r_recirc_fan_pos_off,
		r_pack_pos_high,
		r_pack_pos_auto,
		r_pack_pos_off,
		isolation_valve_pos_open,
		isolation_valve_pos_auto,
		isolation_valve_pos_close,
		l_pack_pos_high,
		l_pack_pos_auto,
		l_pack_pos_off,
		l_recirc_fan_pos_auto,
		l_recirc_fan_pos_off,
		bleed_air_2_pos_off,
		bleed_air_2_pos_on,
		bleed_trip_reset_pb_on,
		bleed_trip_reset_pb_off,
		bleed_air_apu_pos_off,
		bleed_air_apu_pos_on,
		bleed_air_1_pos_off,
		bleed_air_1_pos_on,
		position_light_pos_strobe,
		position_light_pos_off,
		position_light_pos_steady,
		acdc_maint_pos_on,
		acdc_maint_pos_off,

		dc_knob_stby_pwr,
		dc_knob_bat_bus,
		dc_knob_bat,
		dc_knob_aux_bat,
		dc_knob_tr1,
		dc_knob_tr2,
		dc_knob_tr3,
		dc_knob_test,

		ac_knob_stby_pwr,
		ac_knob_gnd_pwr,
		ac_knob_gen1,
		ac_knob_apu,
		ac_knob_gen2,
		ac_knob_inv,
		ac_knob_test,

		Switch_position_unused,
		kMaxValue = Switch_position_unused,
	};
}

