#pragma once

typedef struct {
	int nSwitch;
	int nDirection;
} SWITCHINFO;

/**
 * Device Notification
 */
#define INTERFACEIT_DEVICE_REMOVAL			0x01
#define INTERFACEIT_DEVICE_ARRIVAL			0x02

/**
 *	Switch direction information
 */
#define INTERFACEIT_SWITCH_DIR_UNKNOWN		0xFF
#define INTERFACEIT_SWITCH_DIR_UP			0x0
#define INTERFACEIT_SWITCH_DIR_DOWN			0x1

/**
 *	Board options
 */
#define INTERFACEIT_BOARD_OPTION_NONE		0x0
#define INTERFACEIT_BOARD_OPTION_CDUKEYS	0x1		// CDU v9 does not need this
#define INTERFACEIT_BOARD_OPTION_FORCE64	0x2		// Requred for the new FDS-CONTROLLER-MCP boards for relay to function
#define INTERFACEIT_BOARD_OPTION_RESERVED3	0x4

/**
 *	Error codes
 */
#define IITAPI_ERR_BASE												0

#define IITAPI_ERR_OK							(IITAPI_ERR_BASE -  0)
#define IITAPI_ERR_CONTROLLERS_OPEN_FAILED		(IITAPI_ERR_BASE -  1)
#define IITAPI_ERR_CONTROLLERS_ALREADY_OPENED	(IITAPI_ERR_BASE -  2)
#define IITAPI_ERR_CONTROLLERS_NOT_OPENED		(IITAPI_ERR_BASE -  3)
#define IITAPI_ERR_INVALID_HANDLE				(IITAPI_ERR_BASE -  4)
#define IITAPI_ERR_INVALID_POINTER				(IITAPI_ERR_BASE -  5)
#define IITAPI_ERR_INVALID_CONTROLLER_NAME		(IITAPI_ERR_BASE -  6)
#define IITAPI_ERR_FAILED						(IITAPI_ERR_BASE -  7)
#define IITAPI_ERR_INVALID_CONTROLLER_POINTER	(IITAPI_ERR_BASE -  8)
#define IITAPI_ERR_INVALID_CALLBACK				(IITAPI_ERR_BASE -  9)
#define IITAPI_ERR_RETRIEVING_CONTROLLER		(IITAPI_ERR_BASE - 10)
#define IITAPI_ERR_NOT_ENABLED					(IITAPI_ERR_BASE - 11)
#define IITAPI_ERR_BUFFER_NOT_LARGE_ENOUGH		(IITAPI_ERR_BASE - 12)
#define IITAPI_ERR_BUFFER_NOT_LARGE_ENOUGHT		(IITAPI_ERR_BASE - 12)	// Previous release typo
#define IITAPI_ERR_PARAMETER_LENGTH_INCORRECT	(IITAPI_ERR_BASE - 13)
#define IITAPI_ERR_PARAMETER_OUT_OF_RANGE		(IITAPI_ERR_BASE - 14)
#define IITAPI_ERR_FEATURE_NOT_AVAILABLE		(IITAPI_ERR_BASE - 15)
#define IITAPI_ERR_ALREADY_ENABLED				(IITAPI_ERR_BASE - 16)
#define IITAPI_ERR_NO_ITEMS						(IITAPI_ERR_BASE - 17)
#define IITAPI_ERR_CONTROLLER_ALREADY_BOUND		(IITAPI_ERR_BASE - 18)
#define IITAPI_ERR_NO_CONTROLLERS_FOUND			(IITAPI_ERR_BASE - 19)
#define IITAPI_ERR_UNKNOWN						(IITAPI_ERR_BASE - 20)
